# Generated by Django 6.0.3 on 2026-03-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_control', '0002_station_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.TextField(max_length=200, verbose_name='Название станции/объекта'),
        ),
    ]
