# Generated by Django 6.0.3 on 2026-03-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_control', '0003_alter_station_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название станции/объекта'),
        ),
    ]
