# Generated by Django 6.0.3 on 2026-03-26 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_control', '0004_alter_station_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='registration_date',
        ),
    ]
