from django.urls import path
from .views import (TasksIndexView,
                    BugsListView,
                    StationListView,
                    StationDetailView,
                    StationCreateView,
                    BugCreateView,
                    BugDetailView,
                    BugUpdateView,
                    StationUpdateView,
                    MyBugsListView,
                    AlarmListView,
                    StationsExportView,
                    TasksExportView,
                    KnowledgeListView,
                    KnowledgeCreateView,
                    KnowledgeDeleteView,
                    ContactView,
                    )

app_name = "signal1520"

urlpatterns = [
    path("", TasksIndexView.as_view(), name="index"),
    path("bugs/", BugsListView.as_view(), name="bugs_list"),
    path("bugs/my/", MyBugsListView.as_view(), name="bugs_list_my"),
    path("bugs/<int:pk>/", BugDetailView.as_view(), name="bug_details"),
    path("bugs/create/", BugCreateView.as_view(), name="create_bug"),
    path("bugs/<int:pk>/update/", BugUpdateView.as_view(), name="bug_update"),
    path("bugs/export/", TasksExportView.as_view(), name="bugs_export"),
    path("stations/", StationListView.as_view(), name="station_list"),
    path("stations/<int:pk>/", StationDetailView.as_view(), name="station_details"),
    path("stations/create/", StationCreateView.as_view(), name="create_station"),
    path("stations/<int:pk>/update/", StationUpdateView.as_view(), name="station_update"),
    path("stations/export/", StationsExportView.as_view(), name="stations_export"),
    path("alarms/", AlarmListView.as_view(), name="alarm_list"),
    path("knowledge/", KnowledgeListView.as_view(), name="knowledge_list"),
    path("knowledge/create/", KnowledgeCreateView.as_view(), name="knowledge_create"),
    path("knowledge/<int:pk>/delete/", KnowledgeDeleteView.as_view(), name="knowledge_delete"),
    path("contact/", ContactView.as_view(), name="contact"),
]
