# Generated by Django 6.0.4 on 2026-04-19 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can_view_users_list', 'Может просматривать список пользователей')]},
        ),
    ]
