# Generated by Django 6.0.3 on 2026-04-30 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_profile_knowledge_file_limit'),
        ('signal1520', '0008_organization_alter_station_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='signal1520.organization', verbose_name='Организация'),
        ),
    ]
