# Generated by Django 6.0.4 on 2026-05-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_profile_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='consent_given_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата согласия на обработку ПД'),
        ),
        migrations.AddField(
            model_name='profile',
            name='consent_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP при согласии'),
        ),
        migrations.AddField(
            model_name='profile',
            name='consent_policy_version',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Версия политики'),
        ),
    ]
