"""
Django settings for workflow_monitoring project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
    https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
    https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from django.urls import reverse_lazy
from dotenv import load_dotenv

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# --- РАЗРАБОТКА ---
# SECRET_KEY = 'django-insecure-pc%@sq!y#sbnnsqgmd+s6#2(r+ft$2v(sqo+ir3_%c&y41te68'
# --- ПРОДАКШН ---
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    raise RuntimeError("SECRET_KEY не установлен в переменных окружения")

# SECURITY WARNING: don't run with debug turned on in production!
# --- РАЗРАБОТКА ---
# DEBUG = True
# --- ПРОДАКШН ---
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# --- РАЗРАБОТКА ---
# ALLOWED_HOSTS = []
# --- ПРОДАКШН ---
ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'axes',
    'authentication.apps.AuthenticationConfig',
    'signal1520.apps.Signal1520Config',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # --- ПРОДАКШН: WhiteNoise для раздачи статики (после SecurityMiddleware) ---
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'axes.middleware.AxesMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'workflow_monitoring.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'signal1520.context_processors.org_slug',
            ],
        },
    },
]

WSGI_APPLICATION = 'workflow_monitoring.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if os.environ.get('DATABASE_URL') == 'postgres':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME'),
            'USER': os.environ.get('DB_USER'),
            'PASSWORD': os.environ.get('DB_PASSWORD'),
            'HOST': os.environ.get('DB_HOST', 'db'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# --- РАЗРАБОТКА ---
STATIC_URL = 'static/'
STATIC_ROOT = 'static/'
# --- ПРОДАКШН ---
# STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# URL для доступа к медиа-файлам (через веб-сервер)
MEDIA_URL = '/media/'

# Путь к директории, где будут храниться загруженные файлы
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

LOGIN_URL = '/accounts/login/'  # URL для перенаправления неавторизованных пользователей

AUTHENTICATION_BACKENDS = [
    # Axes должен быть первым: проверяет блокировку до проверки пароля
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# --- django-axes: защита от brute force ---
# После 5 неудачных попыток — блокировка на 1 час, потом снимается автоматически.
# Блокируем по имени пользователя (не по IP), чтобы атака с разных адресов
# на один аккаунт тоже блокировалась.
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = timedelta(hours=1)
AXES_LOCKOUT_PARAMETERS = [['username']]
AXES_RESET_ON_SUCCESS = True       # при успешном входе счётчик неудач сбрасывается
AXES_LOCKOUT_TEMPLATE = 'authentication/locked_out.html'
# Реальный IP берём из X-Forwarded-For (Nginx проксирует за собой)
AXES_IPWARE_META_PRECEDENCE_ORDER = ['HTTP_X_FORWARDED_FOR', 'REMOTE_ADDR']
# W006 намеренно игнорируется: блокировка по username достаточна для внутреннего сервиса
SILENCED_SYSTEM_CHECKS = ['axes.W006']

#перенаправлем после регисрации на страницу about_me
LOGIN_REDIRECT_URL = '/signal1520/'  # Куда перенаправлять после успешного входа

LOGOUT_REDIRECT_URL = '/accounts/login/'  # Куда перенаправлять после выхода

# Email (SMTP)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.yandex.ru')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 465))
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
SUPPORT_EMAIL = os.environ.get('SUPPORT_EMAIL', '')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} [{levelname}] {name}: {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO' if DEBUG else 'WARNING',
            'propagate': False,
        },
        'signal1520': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'authentication': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
