# Generated by Django 6.0.3 on 2026-04-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal1520', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmInfo',
            fields=[
                ('number', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Номер аларма')),
                ('description', models.CharField(max_length=600, verbose_name='Описание')),
                ('explanation', models.TextField(max_length=1000, verbose_name='Пояснение')),
            ],
            options={
                'verbose_name': 'Аларм',
                'verbose_name_plural': 'Алармы',
                'ordering': ['number'],
            },
        ),
    ]
