# Generated by Django 6.0.4 on 2026-04-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal1520', '0002_alarminfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='distance',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Дистанция'),
        ),
        migrations.AddField(
            model_name='station',
            name='system',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Система'),
        ),
    ]
