# Generated by Django 6.0.3 on 2026-04-30 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal1520', '0007_knowledge_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ['road__title', 'name'], 'verbose_name': 'Станция', 'verbose_name_plural': 'Станции'},
        ),
        migrations.AddField(
            model_name='station',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='signal1520.organization', verbose_name='Организация'),
        ),
    ]
