# Generated by Django 6.0.3 on 2026-04-30 07:45

from django.db import migrations


def seed_org(apps, schema_editor):
    Organization = apps.get_model('signal1520', 'Organization')
    Station = apps.get_model('signal1520', 'Station')

    org, _ = Organization.objects.get_or_create(slug='signal1520', defaults={'name': 'Signal 1520'})
    Station.objects.filter(organization__isnull=True).update(organization=org)


def unseed_org(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('signal1520', '0008_organization_alter_station_options_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_org, unseed_org),
    ]
