# Generated by Django 6.0.3 on 2026-04-30 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal1520', '0009_seed_signal1520_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roads', to='signal1520.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='system',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='signal1520.organization', verbose_name='Организация'),
        ),
    ]
