# Generated by Django 6.0.4 on 2026-05-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal1520', '0013_equipmenttype_add_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='date_of_manufacture',
            field=models.DateField(blank=True, null=True, verbose_name='Дата изготовления'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='factory_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Заводской номер'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='manufacturer',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Изготовитель'),
        ),
    ]
