# Generated by Django 6.0.3 on 2026-10-07 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal1520', '0016_station_created_by_set_null'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('completed', 'Выполнена'), ('cancelled', 'Отменена')], max_length=20, verbose_name='Из статуса')),
                ('to_status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('completed', 'Выполнена'), ('cancelled', 'Отменена')], max_length=20, verbose_name='В статус')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда изменён')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='signal1520.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Смена статуса задачи',
                'verbose_name_plural': 'Смены статусов задач',
                'ordering': ['-changed_at', '-pk'],
                'default_permissions': (),
            },
        ),
    ]
