# Generated by Django 6.0.3 on 2026-10-07 12:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal1520', '0017_task_status_change'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('task_created', 'Задача создана'), ('task_status', 'Статус задачи изменён'), ('task_comment', 'Комментарий к задаче'), ('task_attachment', 'Вложение к задаче'), ('station_created', 'Объект создан')], max_length=20, verbose_name='Событие')),
                ('text', models.CharField(max_length=300, verbose_name='Текст')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Когда')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to='signal1520.organization', verbose_name='Организация')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events', to='signal1520.station', verbose_name='Объект')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events', to='signal1520.task', verbose_name='Задача')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events', to=settings.AUTH_USER_MODEL, verbose_name='Кто')),
            ],
            options={
                'verbose_name': 'Событие ленты',
                'verbose_name_plural': 'События ленты',
                'ordering': ['-created_at', '-pk'],
                'default_permissions': (),
                'indexes': [models.Index(fields=['organization', '-created_at'], name='activity_org_created_idx')],
            },
        ),
    ]
